# Generated by Django 3.0.5 on 2020-05-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='name')),
                ('descripcion', models.CharField(max_length=200, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Hamburguesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='name')),
                ('precio', models.IntegerField(verbose_name='price')),
                ('descripcion', models.CharField(max_length=200, verbose_name='description')),
                ('imagen', models.CharField(max_length=200, verbose_name='img')),
                ('ingredientes', models.ManyToManyField(to='burguer.Ingrediente', verbose_name='Lista de ingredientes')),
            ],
        ),
    ]
