# Generated by Django 3.0.5 on 2020-05-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, to='burguer.Ingrediente', verbose_name='Lista de ingredientes'),
        ),
    ]
