# Generated by Django 3.0.5 on 2020-05-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0002_auto_20200501_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, related_name='hamburguesas', to='burguer.Ingrediente', verbose_name='Lista de ingredientes'),
        ),
    ]
