version: "3"

services:
  db:
    image: postgres
    env_file:
      - .env.db
  web:
    build: .
    command: bash -c "python manage.py migrate"
    volumes:
      - .:/mapsy
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
      - .env.db
